# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SVGPodTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SVGPodTest

  target 'SVGPodTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SVGPodTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SVGPodTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SVGPodTest-tvOS

  target 'SVGPodTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
